# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationReport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationreport',
            name='document',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='evaluationreport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments'),
        ),
        migrations.AlterField(
            model_name='groupofcharacteristics',
            name='evaluationreport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.RequiredCertificationDocuments'),
        ),
        migrations.DeleteModel(
            name='EvaluationReport',
        ),
    ]
