# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_certification_submission_reason_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='submission_reason_other',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
