# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-15 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20180321_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='planned_steps',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='revision_ECM',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='revision_last',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='submission_reason',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='submission_reason_other',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='supplier',
        ),
    ]
