# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20180515_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.CharField(default='', max_length=140)),
                ('next_cycle', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
