# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_garden'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration_set', models.CharField(default='', max_length=140)),
                ('next_cycle_set', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
