# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_gardenset'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='luminosity',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='garden',
            name='recirculation_pump',
            field=models.CharField(default='', max_length=140),
        ),
    ]
