# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_auto_20180524_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='cycle_time',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='garden',
            name='plant_pump',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='garden',
            name='solution_pump',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='gardenset',
            name='plant_pump_set',
            field=models.CharField(default='', max_length=140),
        ),
    ]
