# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagingDescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingdescription',
            name='document',
        ),
        migrations.AlterField(
            model_name='packagingrequirements',
            name='packaging_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments'),
        ),
        migrations.AlterField(
            model_name='supplierpackagingdescription',
            name='packaging_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments'),
        ),
        migrations.DeleteModel(
            name='PackagingDescription',
        ),
    ]
