# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processMap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmap',
            name='document',
        ),
        migrations.AlterField(
            model_name='processstep',
            name='process_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments'),
        ),
        migrations.DeleteModel(
            name='ProcessMap',
        ),
    ]
